### ISSUE TITLE
Quoted path

### ISSUE THREAD

**Issue by Snuff-Daddy** [complexlogic/loudgain#110]
A quoted path is not working.  As a result, rsgain is unusable on any path that contains spaces.

Example:
```
rsgain easy "c:\foo bar"
[FAILURE] Directory 'c:\foo bar"' does not exist
```

**Comment by complexlogic** [comment]
There is a double quotation mark in the directory path, which should not be there. The system shell should remove it when parsing the arguments. Do you have a typo?

**Comment by Snuff-Daddy** [comment]
As you can see for yourself there is no typo.  The error message shows that it is not removing the trailing quote.  This is on Windows 11.

**Comment by complexlogic** [comment]
Which shell are you using?

**Comment by Snuff-Daddy** [comment]
Just the regular cmd.exe

**Comment by Young-Lord** [comment]
Cannot reproduce on `Windows Server 2019, version 1809` or `Windows 11, version 22H2` with `cmd.exe` and `rsgain 3.5`.
```
E:>rsgain easy "E:\a b"
[OK] Building directory tree...
[OK] Found 1 directory...
[OK] Scanning directory for files...
[OK] Scanning 'E:\a b\1.mp3'
...
Track: E:\a b\1.mp3
...
Scanning Complete
Time Elapsed:      00:00:00
Files Scanned:     1
...
```

**Comment by Snuff-Daddy** [comment]
Try it with a trailing slash:

`rsgain easy "E:\a b\"`

**Comment by Young-Lord** [comment]
> Try it with a trailing slash:
> 
> `rsgain easy "E:\a b\"`

With a a trailing slash, this error happens.
However, you didn't mention that in your first comment, where you say you are using `rsgain easy "c:\foo bar"` instead of `rsgain easy "c:\foo bar\"`
This is by design, and not a rsgain bug. See <https://stackoverflow.com/questions/9287812/backslash-and-quote-in-command-line-arguments>
In short, `always escape quotes; only escape backslashes if they precede a quote.` ([source](https://weblogs.asp.net/jongalloway/_5B002E00_NET-Gotcha_5D00_-Commandline-args-ending-in-_5C002200_-are-subject-to-CommandLineToArgvW-whackiness))

**Comment by Snuff-Daddy** [comment]
A user is not going to be even the slightest bit impressed that you are technically correct.  A quote mark is not a legal character in a path, therefore it does not hurt in any way if you remove quotes.  First rule of software development: don't needlessly bust the user's balls.

**Comment by Young-Lord** [comment]
> A quote mark is not a legal character in a path

Wrong.
Open Linux / macOS / WSL , type: `touch \"`, then `ls`,
Then you can see `"` is absolutly a valid path (at least on some filesystems)

That's also another rule of software development: principle of least astonishment.

> A user is not going to be even the slightest bit impressed that you are technically correct.

Also as a user tweaking CLI tool and music metadata using binary from GitHub / Package manager, I suppose this person do have sufficient knowledge on argument escaping and correcting.

**Comment by complexlogic** [comment]
@Snuff-Daddy As I mentioned in my first comment, it's the responsibility of the system shell to parse the command line into individual arguments. That's not something I can control as the program author. So this is out of the scope of this issue tracker, but I'm glad @Young-Lord was able to help you find the solution for your issue.
