### ISSUE TITLE
MacOs hidden files block scanning

### ISSUE THREAD

**Issue by MrYann** [complexlogic/loudgain#112]
I execute rsgain on Linux Debian 12 through ssh and hidden files generated by the MacOs file explorer block the flow.

The music folders were previously opened by a MacOs computer, which generated numerous small files with the same name as the original files but preceded by ._ (and are thus hidden).
Example: in a folder containing song.mp3, after viewing the folder through "Finder" (the MacOs file explorer) it will also contain a small file named ._song.mp3.

It seems that those ._xxx files confuse rsgain to he point of doing nothing to the rest of the folder.

Sample output:
```
rsgain easy -Os '/DATA/Media/Musique/Joe Satriani - The Elephants of Mars FLAC'
[✔] Building directory tree...
[✔] Found 1 directory...
[✔] Scanning directory for files...
[✔] Scanning '/DATA/Media/Musique/Joe Satriani - The Elephants of Mars FLAC/._03. Faceless.m4a'
[✘] Could not open input: Invalid data found when processing input

No files were scanned
```
The folder contains 14 tracks and I see no log file generated whatsoever.

Please let me know if you need more information.

**Comment by complexlogic** [comment]
It should be straightforward to add a simple check if a filename begins with `._`. I'll implement this in the near future.

**Comment by MrYann** [comment]
That would do it. However, I suggest you should rather handle « bad » files so that the script skips to the next file instead of skipping to the next folder. Of course, it is easier to ask than to do ;)

**Comment by complexlogic** [comment]
Yes, that is the plan. Any file beginning with `._` will be ignored.

**Comment by MrYann** [comment]
To be more résilient, i would suggest to make the script go to next song instead of skipping to next folder when encountering corrupt files. Here, the`._name.mp3` files can be ignored by the name pattern, but this does not cover other cases of corrupt files being processed and leading to the whole folder being ignored.
