### ISSUE TITLE
Outdated fmt dependency

### ISSUE THREAD

**Issue by audiomuze** [complexlogic/loudgain#127]
Arch Linux has moved to fmt-11.0.2-1, rsgain has a dependency on 10.

[****](rsgain: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory)

**Comment by complexlogic** [comment]
Your current *build* of rsgain depends on fmt10 only, but the program *source* does not; it can work with both 10 and 11. To fix the error, you just have to rebuild rsgain. For example, if using `yay`:

`yay -S --rebuild rsgain`
