### ISSUE TITLE
Skip not skipping on windows?

### ISSUE THREAD

**Issue by gkdwoe** [complexlogic/loudgain#129]
When running rsgain easy F:\music -m MAX --skip-existing on Windows, it processes all files regardless of their ReplayGain tags. In contrast, it works as intended on Linux, applying ReplayGain only to files without existing tags.

**Comment by complexlogic** [comment]
I was not able to reproduce this on my Windows setup. The skip tags function is working as expected for me.

Can you give a little more information about your Windows setup? Are you running the command on the same files between your Windows and Linux setups, or on different files?

**Comment by gkdwoe** [comment]
I just did some testing, and the issue was related to how I was using the command. I was running: rsgain easy $file -m MAX --skip-existing. It turns out that everything after $file was being ignored, though I'm not sure if this behavior was intentional or not.

**Comment by complexlogic** [comment]
In the command line syntax, options like `--skip-existing` always need to come before positional arguments (in this case, the directory to scan). So this is expected behavior.
