### ISSUE TITLE
cmath vs math.h headers

### ISSUE THREAD

**Issue by diizzyy** [complexlogic/loudgain#17]
Based on https://cgit.freebsd.org/ports/tree/audio/rsgain/files/patch-src_tag.cpp there might be more occurrences where this needs to be reviewed.

Explains the issue in more detail
https://stackoverflow.com/questions/10694255/cmath-vs-math-h-and-similar-c-prefixed-vs-h-extension-headers/64444869#64444869

**Comment by complexlogic** [comment]
Yeah, this was an oversight on my part, but GCC didn't catch it for me

**Comment by complexlogic** [comment]
Fixed by #18
