### ISSUE TITLE
Missing dependency [ubuntu]

### ISSUE THREAD

**Issue by 888B8888** [complexlogic/loudgain#2]
`rsgain: error while loading shared libraries: libinih.so.1: cannot open shared object file: No such file or directory`

Fixed by installing `libinih1`

**Comment by complexlogic** [comment]
Looks like I forgot that one in the package config. I'll go ahead and add it now. Thanks for the report.

**Comment by complexlogic** [comment]
The .deb package on the Release page has been updated.
