### ISSUE TITLE
Consider publishing source code archives for releases

### ISSUE THREAD

**Issue by diizzyy** [complexlogic/loudgain#20]
It would be helpful if static source code archives would be generated for releases as it makes packaging more reliable

**Comment by complexlogic** [comment]
GitHub automatically generates a .tar.gz and .zip archive of the source code for every release. Are you referring to something different?

**Comment by diizzyy** [comment]
Yes, those are generated on the fly.
See https://github.com/xiph/flac/releases/tag/1.4.2 for example (Assets)

**Comment by complexlogic** [comment]
Thanks for that example. What are the advantages of source packages as an asset versus the GitHub generated ones?

**Comment by diizzyy** [comment]
The source package is static, meaning that even if GitHub's infrastricture changes (different set of git hashes, compression etc) you'll still have a valid source archive. https://github.com/bazelbuild/bazel/issues/3722 (there are a lot of other reports about this)

edit: fwiw, this is also true for GitLab etc
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12494

**Comment by complexlogic** [comment]
I think this is a good idea. I'm currently attempting to set up a CI for this project, I'll look into automatic generation of source packages.

**Comment by complexlogic** [comment]
I got the CI working. It publishes an LZMA-compressed tar archive of the source code for every release, and it also appends the SHA256 sum to the release notes for packagers.

**Comment by diizzyy** [comment]
That's great!
