### ISSUE TITLE
Wishlist - xHE-AAC / USAC support

### ISSUE THREAD

**Issue by diizzyy** [complexlogic/loudgain#27]
It would be nice if rsgain would support this format however support is a bit troublesome in FFmpeg

[✘] Could not open codec: 'Function not implemented'

Reference:
https://hydrogenaud.io/index.php/topic,118888.msg1011212.html#msg1011212

```
ffmpeg -i sample-xhe-aac.m4a -f wav -acodec pcm_s16le moo.wav
[aac @ 0x83bbc0500] Audio object type 42 is not implemented.
```

```ffmpeg -acodec libfdk_aac -i sample-xhe-aac.m4a -f wav -acodec pcm_s16le foo.wav```
Works

From what I can tell you should be able to probe for a specific codec
https://www.ffmpeg.org/doxygen/4.4/group__lavc__core.html#ga776f2359007e8457799503068419e791

**Comment by complexlogic** [comment]
Check out the new feature branch `aac`. The xHE-AAC files will now scan correctly, assuming your FFmpeg was compiled with `--enable-libfdk-aac`.

The only drawback I've noticed as that the libfdk-aac is slower than libavcodec's built-in AAC decoder for regular AAC files. So I think I may implement this as a compile-time option and disabled by default.

**Comment by diizzyy** [comment]
I think a better approach would be to use FFmpeg's default AAC decoder and fall back to/try fdk-aac before failing instead of hardcoding one over another.

**Comment by complexlogic** [comment]
Yeah, you're right, that implementation was a bit lazy. I just updated it so that it tries the FFmpeg decoder first, and if it fails it falls back to fdk-aac.

**Comment by diizzyy** [comment]
Works fine on my end, thanks!
