### ISSUE TITLE
small bug: --clip-mode

### ISSUE THREAD

**Issue by atomGit** [complexlogic/loudgain#41]
```
rsgain custom --tagmode='i' --clip-mode='n' -- *.flac
[✘] Unrecognized option 'c'
```

the short option works though (-c n)

rsgain-git 3.1.1 (AUR)
manjaro linux

**Comment by complexlogic** [comment]
Thanks for the report. This has an easy fix

**Comment by atomGit** [comment]
i'd appreciate if you'd fix these bugs a little faster LOL

thanks!

i'm impressed by the speed of yours vs. loudgain, plus fewer deps
