### ISSUE TITLE
rsgain chokes on large file names

### ISSUE THREAD

**Issue by SimonHova** [complexlogic/loudgain#45]
When scanning my music folder, it stops on the infamous Fiona Apple [release](https://musicbrainz.org/release-group/3d3ff0b9-5858-33f3-9d67-8ba5977899a8) with the very very very long name. It gives my preferred [music player](https://github.com/ampache/ampache) [fits](https://github.com/ampache/ampache/issues/3342) as well.

Last line when scanning gives a clue, but I can enable logging as well if needed
`  10.1% Scanning directory '/media/Take/Music/Apple, Fiona/[1999] When the Pawn Hits the Conflicts He Thinks Like a King What He Knows Throws the Blows When He Goes to the Fight and Segmentation faultirectory '/media/Take/Music/Various Artists/[2019] Paste Studio Sampler #5 - October 2019'...`

**Comment by complexlogic** [comment]
Could you try scanning that particular directory without multithreading enabled and post the output?

**Comment by SimonHova** [comment]
How interesting! It did it perfectly when I isolated just the handful of directories under the artist's name. Tried it both with and without multi-threading.

I am going to try and run it again, but now with the logging turned on. I should have a more accurate idea of where it's crashing. I'll update you shortly.

**Comment by SimonHova** [comment]
...stumbled on another odd issue, submitted a new [report](https://github.com/complexlogic/rsgain/issues/46).

**Comment by complexlogic** [comment]
> I am going to try and run it again, but now with the logging turned on. I should have a more accurate idea of where it's crashing. I'll update you shortly.

There is no extra logging function. What you see currently is what is available. One option that may help is to run it in `gdb` if you know how to do that. That would allow you to trace to segfault.

**Comment by SimonHova** [comment]
Sorry, I was not clearer, the logging function that I was referring to was the output of the .csv files placed in each folder. I am assuming that I can search for the last file created, and use that as a clue to where the process stopped.

However, my testing makes it look irrelevant, as I'm now unable to recreate the problem. I will try to run the process again overnight and report back in the morning. Hopefully, I'll be able to close it without any problems.

**Comment by Rycia** [comment]
I'm also having a relative issue with a directory of the following:
`"M:\Music\B\Bring Me The Horizon\[2010] There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret\Bring Me The Horizon - There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret. - 1 12 - The Fox And The Wolf.mp3"`
That's one directory. And all the files inside work except for just two:
`Bring Me The Horizon - There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret. - 1 11 - Blessed With A Curse.mp3`
`Bring Me The Horizon - There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret. - 1 12 - The Fox And The Wolf.mp3`

Running with MAX thread parameter. They seem to be the longest filenames in the whole directory.
The shorter of the 2 is 266 chars, so likely there's a limit between 261 and 266 (based on the shorter path). I'd estimate there's a 264 limit.

I would also add that the command prompt hangs if ran on only the problematic directory, and it works if I make the directory shorter.

**Comment by Rycia** [comment]
I'm also having this problem. The full length character limit is 255.

**Comment by Hate9** [comment]
oh dear, I am also having this issue.

**Comment by phw** [comment]
> Bring Me The Horizon - There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret. - 1 12 - The Fox And The Wolf.mp3

The length of these paths is slightly over the path length limitation of the Windows API, which is at 259 characters (+ a trailing null)*. So it can't be accessed by traditional Windows API calls without some extra work.

Microsoft is trying to get rid of this limitation, but it proves difficult. In newer Windows versions log path support can be enabled in Windows registry, but applications also must opt-in into this.

One way for you to handle this would be to prefix the path with `\\?\`, which indicates to the Windows API to pass the path unchanged to the underlying filesystem. So your path would be:

`"\\?\M:\Music\B\Bring Me The Horizon\[2010] There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret\Bring Me The Horizon - There Is A Hell, Believe Me I’ve Seen It. There Is A Heaven, Let’s Keep It A Secret. - 1 12 - The Fox And The Wolf.mp3"`

See also https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

---
*) To clarify the limits a bit: The above article says the path limit is 256 characters. This is without the three character directory part, e.g. "M:\".

**Comment by complexlogic** [comment]
@phw Thanks for your help in debugging this.

I have previously tried to recreate the path specified by @Rycia. Despite changing the registry settings to enable long paths, I was unsuccessful in my attempt to create the long path, with both Windows Explorer and shell commands. I can't reproduce this issue until I can create a long path for testing purposes.

I am wondering if the type of the underlying filesystem has something to do with this. Is `M:\` a removable storage drive, perhaps?

**Comment by phw** [comment]
I spent quite some time dealing with this in Picard. It's annoying really. Windows Explorer does not yet support long paths, no matter the registry setting. Command line should work if you use the `\\?\` prefix

You should be able to create such a path using the normal Windows API when using the prefix I described above. AFAIK it only works with absolute paths.

One easy way would be to use Picard to write a long file. But you need to enable long path support in Options > File naming > Compatibility.

> I am wondering if the type of the underlying filesystem has something to do with this. Is M:\ a removable storage drive, perhaps?

Removable should not make a difference. But filesystem. The above prefix thing definitely works for NTFS. FAT filesystem I think does not allow long paths at all. Network shares should also work but depends on the server and needs another prefix (it's mentioned in the MS docs I linked above)

**Comment by complexlogic** [comment]
Adding `longPathAware` to the Windows app manifest fixed the issue.

I created a test file with a path length of 277 characters. Verified that it scans correctly using the build with the new app manifest, and verified that it fails to scan using an old build.

For those affected by this issue, you can use the [development build](https://github.com/complexlogic/rsgain/actions/runs/7241167423/artifacts/1120208438) from the CI until the next release.
