### ISSUE TITLE
Can't build on macOS Big Sur (11.6.8)

### ISSUE THREAD

**Issue by operationalconglomerate** [complexlogic/loudgain#5]
Using the default compiler (Apple clang version 13.0.0 (clang-1300.0.29.30)) it never finishes building, due to "implicit instantiation of undefined template".
If I brew install gcc-12, it builds (with lots of warnings) but can't seem to properly open files for analysis.
See attachments.  Any help would be appreciated!
[rsgain.clang.txt](https://github.com/complexlogic/rsgain/files/9460412/rsgain.clang.txt)
[rsgain.gcc.txt](https://github.com/complexlogic/rsgain/files/9460413/rsgain.gcc.txt)

**Comment by complexlogic** [comment]
Looks like I forgot to include the header for the stringstream class. Some compilers will find it for you automatically and some don't. I uploaded the fix in a new branch `clang_fix`. You can get it with:
```
git clone -b clang_fix https://github.com/complexlogic/rsgain.git
```
Please rebuild with Clang and let me know if it fixes your issue.

As for your second issue, I can see that FFmpeg was not able to properly detect the audio properties of the file, which explains why opening SWResample later fails.
```
[✔] Stream #0: AAC (Advanced Audio Coding), 0 Hz, 0 ch, 0 channels
```
I am hoping that this is due to some ABI incompatibility between Clang and GCC and will be resolved when you rebuild rsgain with Clang. Please let me know.

**Comment by operationalconglomerate** [comment]
Wow, thank you for the incredibly fast response!  

The patch enables it to be built with native clang.  When I run it, it still has the same problem as the gcc-compiled version:
rsgain/build> ./rsgain easy ../../Wired/
[✔] Building directory tree
[✔] Scanning directory: ../../Wired/
[✔] Scanning '../../Wired/03 Goodbye Pork Pie Hat.m4a' ...
[✔] Container: QuickTime / MOV [mov,mp4,m4a,3gp,3g2,mj2]
[✔] Stream #0: AAC (Advanced Audio Coding), 0 Hz, 0 ch, 0 channels
[✘] Could not open SWResample: Invalid argument

My next guess is that I have my homebrew libraries and headers socked away in a non-standard location, since I didn’t want to make /usr/local world writable.  I manually added the library path into CMakeLists.txt with link_directories, which I figured would be good enough.

  -- MW

**Comment by complexlogic** [comment]
Could you please run `ffmpeg -i "../../Wired/03 Goodbye Pork Pie Hat.m4a"` and post the output? Also, please run `rsgain -v` so we can verify the library versions match

**Comment by operationalconglomerate** [comment]
I haven’t had any ffmpeg problems lately.  Not sure where the disconnect lies, but I’ll be happy to help poke around more ;)

(hackintosh) ~/tmp/bar/rsgain/build> ffmpeg -i "../../Wired/03 Goodbye Pork Pie Hat.m4a"
ffmpeg version 4.4.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-libzimg --enable-libzvbi --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --enable-zlib --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --disable-securetransport --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-libdav1d --enable-libaom --enable-librav1e --enable-libsvtav1 --arch=x86_64 --enable-x86asm --enable-gpl --enable-postproc --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvidstab --enable-nonfree --enable-libfdk-aac
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa2a3810800] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../../Wired/03 Goodbye Pork Pie Hat.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 1999-02-15T12:02:19.000000Z
    iTunSMPB        :  00000000 00000840 000002F0 0000000000DD9CD0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    iTunNORM        :  0000067E 000006D3 00004F49 00006FBF 000411FF 0000F6B6 00007FF3 00007FF1 00024D35 00040F18
    title           : Goodbye Pork Pie Hat
    artist          : Jeff Beck
    album           : Wired
    genre           : Rock
    track           : 3/8
    date            : 1976
    comment         : Charlie Mingus
    compilation     : 0
    account_id      : ***@***.***
    account_type    : 0
    media_type      : 1
  Duration: 00:05:29.40, start: 0.047889, bitrate: 289 kb/s
  Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 274 kb/s (default)
    Metadata:
      creation_time   : 1999-02-15T12:02:19.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 300x298 [SAR 1:1 DAR 150:149], 90k tbr, 90k tbn, 90k tbc (attached pic)
At least one output file must be specified
Exit 1

**Comment by complexlogic** [comment]
You have multiple conflicting installations of FFmpeg: version 5.1 via Homebrew, and version 4.4.2 at `/opt/local` from some other source. My theory is that your issue is being caused by ABI incompatibility: rsgain was compiled against FFmpeg 5.1, but 4.4.2 is being loaded at runtime. On Unix systems, linking against a particular shared object file does not guarantee that it will be actually loaded at runtime. You can verify which library versions rsgain has loaded at runtime with `rsgain -v`.

If you do find that the loaded FFmpeg libraries are from 4.4.2 (library versions match your post above), you will need to force the loader to use the Homebrew-provided FFmpeg 5.1 libraries. On Linux, you would use the environment variable `LD_LIBRARY_PATH`. Apparently this does not exist on macOS, but it appears there is an equivalent `DYLD_LIBRARY_PATH`. So try running rsgain like this:
```
DYLD_LIBRARY_PATH=$(brew --prefix)/lib:$DYLD_LIBRARY_PATH rsgain
```

**Comment by operationalconglomerate** [comment]
Brilliant deduction!  Yes, I use macports (/opt/local) and homebrew ($HOME/.homebrew) because they support mutually exclusive packages.  I’ve never run into this problem before with compiling/linking with the wrong version.  

Unfortunately, the DYLD_LIBRARY_PATH shell variable doesn’t seem to be honored. That said, I was able to prove your theory by uninstalling ffmpeg from /opt/local, and rsgain now works as advertised. I guess I’ll have to research a way to keep two incompatible ffmpegs installed on my system, but that’s not an issue with rsgain.

Thank you so much for solving my problems with rsgain in less than a day!

  -- MW

**Comment by complexlogic** [comment]
It's generally not a good idea to keep multiple conflicting versions of a library unless you absolutely need to for compatibility purposes. rsgain is compatible with both FFmpeg 4 and FFmpeg 5. If you have nothing else that requires FFmpeg 5 specifically, you should just use FFmpeg 4. 

In that case, uninstall the `ffmpeg` package from Homebrew, then delete everything in your rsgain build directory (to make sure nothing is cached). Generate the makefile with:
```
PKG_CONFIG_PATH=/opt/local/lib/pkgconfig:$PKG_CONFIG_PATH cmake ..
```
That environment variable should allow CMake to detect your macports FFmpeg libraries. It will print the library version numbers so you can verify. If all is good, then you can go ahead and build and you shouldn't have any more conflicts.
