### ISSUE TITLE
presets folder lookup path is invalid when program is executed through symlink

### ISSUE THREAD

**Issue by TETYYS** [complexlogic/loudgain#55]
Platform: Windows

If application is executed through a symlink, presets folder lookup path is based on base path of symlink, not the .exe itself where presets folder is also located

**Comment by complexlogic** [comment]
Apparently Windows does not resolve symlinks in process names, so it may not be very straightforward to support symlinking in this manner. An alternative option would be to search for a standard preset folder in the user's home directory, based on an environment variable. For example, on macOS, it will search `~/Library/rsgain/presets`. I would be open to doing something similar for Windows. This would fulfill the same purpose of having a stable location to save presets that does not depend on the binary location.

Also, searching presets by name is just a convenience feature. You can always use the path to the preset.

**Comment by TETYYS** [comment]
> Also, searching presets by name is just a convenience feature. You can always use the path to the preset.

I haven't tried it, but according https://github.com/complexlogic/rsgain/blob/master/src/easymode.cpp#L526 it doesn't look like so.

Searching in user folder would be a good solution

**Comment by complexlogic** [comment]
That only executes if the preset argument has no detected file extension. The logic is that if it has a file extension, then it must be a path. If it has no file extension, then it must be a name and the program should search for it in the default locations.

I am fine with adding a default user location for Windows presets if you can provide examples of paths where config files are typically stored for a Windows command line program, i.e. what are other programs using.

**Comment by TETYYS** [comment]
it's an anarchy on windows but i've got 39 folders starting with dot in my `%userprofile%` folder so that could be it

**Comment by complexlogic** [comment]
Perhaps `%userprofile%\.rsgain\presets` would be a reasonable location then. That would be similar enough to what is being done on macOS and Linux.

**Comment by sergeevabc** [comment]
``` console
$ rsgain --version
rsgain 3.4 - using:
   libebur128     1.2.6
   libavformat    60.3.100
   libavcodec     60.3.100
   libavutil      58.2.100
   libswresample  4.10.100

Built with:
   TagLib         1.13.1

Compiler:         Microsoft C/C++ 19.35
Build Date:       2023-09-12

$ rsgain -p no_album custom hello.mp3
[FAILURE] Unrecognized option 'p'
```

Why?

**Comment by complexlogic** [comment]
@sergeevabc You forgot to specify the mode. Should be `rsgain easy` or `rsgain custom`.

**Comment by sergeevabc** [comment]
<kbd>![2023-1207-1951 rsgain custom](https://github.com/complexlogic/rsgain/assets/373718/54f71070-3371-4023-b16f-1f73cb69dc21)</kbd>

I specified the mode. Check again.

**Comment by phw** [comment]
Two things here:

1. The parameters for a subcommand must come first, so first the subcommand `custom`, then the parameters
2. The preset parameter is for easy mode. easy mode works with presets, custom mode is for specifying all parameters on the command line

So a proper command in your case might be

    rsgain easy -p no_album hello.mp3

**Comment by sergeevabc** [comment]
@phw, no, easy mode can't be used with file names, dirs only as follows

``` console
$ rsgain easy -p no_album hello.mp3
[FAILURE] 'hello.mp3' is not a valid directory

$ rsgain custom -p no_album hello.mp3
[FAILURE] Unrecognized option 'p'
```

Guys, it will be more productive to advise things that you have first tested to work on your computer.

**Comment by TETYYS** [comment]
> @phw, no, easy mode can't be used with file names, dirs only as follows
> 
> ```
> $ rsgain easy -p no_album hello.mp3
> [FAILURE] 'hello.mp3' is not a valid directory
> 
> $ rsgain custom -p no_album hello.mp3
> [FAILURE] Unrecognized option 'p'
> ```
> 
> Guys, it will be more productive to advise things that you have first tested to work on your computer.

it will be more productive to open a new issue instead of dumping your problems in a random place. why am i being notified on this? you did not write what you intend to actually do, you obviously did not read the program documentation, and finally "hello.mp3" is a valid name for a directory, so command that phw posted is perfectly correct

**Comment by sergeevabc** [comment]
@TETYYS,  I want to compute replaygain without album tag for a specific file 'hello.mp3'. That's why I use 'custom' mode (since 'easy' is meant to dirs only) and flag '-p no_album' (according to documentation, which I 'obviously did not read') -- this does not work, input and output (logs) are attached. This is the way I report bugs since 1996. It seems you can't help here, so feel free to unsubscribe to feel less frustrated.

**Comment by complexlogic** [comment]
@sergeevabc If you open a [discussion topic](https://github.com/complexlogic/rsgain/discussions), I will gladly help you there with any problems you are facing. This issue is not the appropriate place for that.
