### ISSUE TITLE
Segmentation fault (core dumped) on some files

### ISSUE THREAD

**Issue by kylxbn** [complexlogic/loudgain#58]
I have been encountering some crashes on a couple of files. I am not sure why these fails, I have verified that the files are not corrupted. Here are a couple of the files that makes rsgain crash.

[rsgain-crash.zip](https://github.com/complexlogic/rsgain/files/11209169/rsgain-crash.zip)

I have a feeling that one of the files is too short (803 milliseconds) but maybe it should just be padded with silence at the end automatically in case it is too short? But for the MP3 file, I have no idea why it crashes.

If I can provide more detail, please tell me.

```
I am running rsgain 3.2.1 - using:
   libebur128     1.2.6
   libavformat    60.3.100
   libavcodec     60.3.100
   libavutil      58.2.100
   libswresample  4.10.100

Built with:
   taglib         1.13.0

Compiler:         GCC 12.2
Build Date:       Apr  2 2023
```

**Comment by complexlogic** [comment]
Thanks for the report. I traced this to the the progress bar. If you run with `-q`, you should notice that it does not crash. The cause is most likely overflow of a buffer that was initialized with zero or invalid size. I will have time to further investigate and provide a fix later this week.

**Comment by kylxbn** [comment]
Awesome! Thank you very much!

**Comment by cirdanlunae** [comment]
> Thanks for the report. I traced this to the the progress bar. If you run with `-q`, you should notice that it does not crash. The cause is most likely overflow of a buffer that was initialized with zero or invalid size. I will have time to further investigate and provide a fix later this week.

Thank you so much for posting a workaround. You kept me from scratching my head for hours!
