### ISSUE TITLE
Not writing to ID3v2 tag

### ISSUE THREAD

**Issue by Dogway** [complexlogic/loudgain#6]
If I don't define lowercase (-L) for custom mode, rsgain won't write track replay gain to ID3v2 tag field.
Using this call:
```rsgain custom -r -k -K -1.0 -s e -d 0.0 -S -I 4 "%%F"```

Is this ok? As uppercase seems to be the standard.

By the way, I'm on Win7 but despite what the readme says it works on this OS as well.

**Comment by complexlogic** [comment]
Which file type are you using? MP3?
> By the way, I'm on Win7 but despite what the readme says it works on this OS as well.

Yes, basic functionality will still work on Windows 7, the main thing you will lack is Unicode support. rsgain uses UTF-8 for Unicode, which is only supported in Windows 10 and later.

**Comment by Dogway** [comment]
Yes, noticed that (UTF-8 lack)
Yes mp3, checked ID3v2 on Winamp v5.666 and Wacup March 2021 Public release.
Wacup still handles to read RG somehow.

**Comment by complexlogic** [comment]
Try MusicBrainz Picard. I know for sure that program will read both upper case and lower case tags.

**Comment by Dogway** [comment]
Thanks, I'm using mp3tag besides mediainfo. Mediainfo shows range and reference in the General section, and peak and gain on the Audio section with `-L -I 4`
Lack of Unicode support is cumbersome but worked around it. The only problem is rerunning `rsgain easy` doesn't overwrite album tags.
