### ISSUE TITLE
Problem: conflicting requests - nothing provides libavformat-free >= 56

### ISSUE THREAD

**Issue by ghost** [complexlogic/loudgain#63]
![Screenshot from 2023-05-16 11-06-33](https://github.com/complexlogic/rsgain/assets/96946370/9e8af126-87c4-4fe2-8e89-b83945eccdf2)

Hi, I'm trying to install rsgain but it fails as in the image.
Fedora says I already have libavformat-free.
Is it possible that there is a typo on version 56, meaning we needed a >= 5.6 version?

**Comment by complexlogic** [comment]
Thanks for the report. This was a simple typo on my part - the 5 and 6 and next to each other on the keyboard and I must have hit both.

I've fixed the issue and rebuilt the package on the release package. Go ahead and try again and it should install successfully now.
