### ISSUE TITLE
std::vector Operator [] Assertion

### ISSUE THREAD

**Issue by famewolf** [complexlogic/loudgain#64]
I added --skip-existing so it would quickly get to where it gave me the error again.

famewolf@TP01-2066  /mnt/tank/shared/media  rsgain easy -m MAX --skip-existing ./music
[✔] Building directory tree...
[✔] Found 3,426 directories...
[✔] Scanning directories for files...
[✔] Scanning with 16 threads...
/usr/include/c++/12.2.1/bits/stl_vector.h:1123: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = ScanJob::Track; _Alloc = std::allocator<ScanJob::Track>; reference = ScanJob::Track&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    1545602 IOT instruction (core dumped)  rsgain easy -m MAX --skip-existing ./music

**Comment by complexlogic** [comment]
I just pushed a new branch `fix` with a check that I think will fix the issue. Can you build the `fix` branch from source and let me know if it fixes the issue?

```
git clone -b fix https://github.com/complexlogic/rsgain.git
```

**Comment by famewolf** [comment]
I did a google to find out how to build it....have it running now...will report back.

**Comment by complexlogic** [comment]
Thanks. Make sure to run using `./rsgain` to make sure you're using the locally built one and not the installed version.

**Comment by famewolf** [comment]
Seems to have done the job.   I renamed the original rsgain and moved the new one to /usr/bin

✘ famewolf@TP01-2066  /mnt/tank/shared/media  rsgain easy -m MAX  ./music                  
[✔] Building directory tree...
[✔] Found 3,426 directories...
[✔] Scanning directories for files...
[✔] Scanning with 16 threads...
 100.0% Scanning directory: ./music/Coldplay/Orphans (Muzi remix) (2019)

Should it be staying at 100% for an extended time?  And of course right after I posted that it wrapped up:

Scanning Complete
Time Elapsed:      02:00:38
Files Scanned:     23,266
Clip Adjustments:  538 (2.3% of files)
Average Gain:      -6.63 dB
Average Peak:      0.949739 (-0.45 dB)
Negative Gains:    21,884 (94.1% of files)
Positive Gains:    1,382 (5.9% of files)

**Comment by complexlogic** [comment]
Thanks for verifying the fix. I'll merge it into `master` now.

**Comment by famewolf** [comment]
Glad to help!  Thanks for making this tool available for us to use!
