### ISSUE TITLE
Work files (and log changes) in alphanumeric order

### ISSUE THREAD

**Issue by csaavedra** [complexlogic/loudgain#66]
I wanted to compare two different versions of an album I have, but it got tedious when I realized that rsgain will process and log the result in what looks like a random order? I had to sort the CSV file later in order to compare results. Would be nice if this all processing and logging was done following alphanumeric order on the filenames.

**Comment by complexlogic** [comment]
The order of filesystem iteration is undefined by the C++ standard and therefore up to the implementation.

It would be relatively easy to implement a `-O` option to sort the tracks alphanumerically for the CSV log. Is there a reason why a user would want them to be actually *scanned* in alphanumeric order (besides the log output)? That could be more complex to implement.

**Comment by csaavedra** [comment]
>  Is there a reason why a user would want them to be actually scanned in alphanumeric order (besides the log output)? 

Probably just because of the log output. In that case just sorting before printing the summary after a whole directory has been scanned would bee enough?

Not sure the `-o`option is really needed, but of course that's up to you :-)

**Comment by complexlogic** [comment]
@csaavedra I implemented this feature. You can invoke by passing 'a' as an argument to the O option. For example, you would use `-Oa` instead of `-O` to get the files sorted alphanumerically for the CSV output.
