### ISSUE TITLE
Default profile ignores OpusMode?

### ISSUE THREAD

**Issue by 239** [complexlogic/loudgain#70]
Changing `OpusMode` in **default.ini** seems to have no effect, no matter what is set in `[Global]` or `[Opus]`:

```
[Global]
Album=true
...
OpusMode=r
TagMode=i
TargetLoudness=-18
TruePeak=false

[Opus]
OpusMode=r

```

Although it does work using a separate profile **opus.ini** (`rsgain easy -S -p opus`):

```
[Global]
TagMode=n

[Opus]
OpusMode=r
TagMode=i
TargetLoudness=-23
```

**Comment by complexlogic** [comment]
Are you explicitly invoking the preset (`-p default`) in your first example? Note that the program does not load the default preset automatically. The reason that file is included is to be used as a template for users to create their own presets. It's not really intended to be used by the program. The settings from that preset are already used internally in the source code.

**Comment by 239** [comment]
My fault, I thought it was more like changing the default settings. Thanks for the clarification!
**defaults.ini**, **example.ini** or **template.ini** might be less confusing in this case.
