### ISSUE TITLE
TagMode n still scans skipped files

### ISSUE THREAD

**Issue by 239** [complexlogic/loudgain#71]
According to [Tag Mode n](https://github.com/complexlogic/rsgain#tag-mode-n) easy mode should skip all files except **.opus** but it still scans and doesn't update other files.
`rsgain easy -S -p opus .../`
**opus.ini**
```
[Global]
TagMode=n

[Opus]
OpusMode=r
TagMode=i
TargetLoudness=-23
```

~~The other way around it scans and even updates **.opus** with all the other files.~~
...

**Comment by complexlogic** [comment]
I can reproduce this in the current `master` build. There was most likely a regression in one of the recent versions. I'll have time to investigate and provide a fix later.
