### ISSUE TITLE
Help to get close to this target

### ISSUE THREAD

**Issue by angelooo18** [complexlogic/loudgain#8]
Hi I want to get my library normalize from ASWG-R001 PORTABLE / Max Integrated: -18 (±2) LKFS / Max True Peak: -1dB.
Im using this line code but I dont know if Im doing it right.
All the songs are in FLAC so this is my config showed in the preset file.

```
rsgain easy -p loudgain -m max "0:/folder/etc"

[FLAC]
#TagMode=i
#Album=true
#TargetLoudness=-18
#ClipMode=a
#MaxPeakLevel=-1.0
#TruePeak=true
```

**Comment by angelooo18** [comment]
All the values was taken from [here](https://youlean.co/loudness-standards-full-comparison-table/)

**Comment by complexlogic** [comment]
The settings are correct, but you need to uncomment them (remove the # character) so they will be read by the program.
```INI
[FLAC]
#TagMode=i
#Album=true
TargetLoudness=-18
ClipMode=a
MaxPeakLevel=-1.0
TruePeak=true
```

**Comment by angelooo18** [comment]
Oh right I can delete the antoher files extension inside the txt?
I have to leave the # in TagMode and Album right?
Or create a new one .ini with that config?

**Comment by complexlogic** [comment]
>Oh right I can delete the antoher files extension inside the txt?

Yes. You can delete anything you don't care about.
> I have to leave the # in TagMode and Album right?

If you keep the # there, it will use the setting in [Global] instead. If you deleted [Global], then uncomment:
```INI
[FLAC]
TagMode=i
Album=true
TargetLoudness=-18
ClipMode=a
MaxPeakLevel=-1.0
TruePeak=true
```

**Comment by angelooo18** [comment]
Oh right Im on that, thank you
