### ISSUE TITLE
Preserve modification times

### ISSUE THREAD

**Issue by xeruf** [complexlogic/loudgain#90]
Coming from r128gain, I am only missing one feature: https://github.com/desbma/r128gain/pull/8/files

```sh
  -p [MTIME_SECOND_OFFSET], --preserve-times [MTIME_SECOND_OFFSET]
                        Preserve modification times of tagged files, optionally adding
                        MTIME_SECOND_OFFSET seconds. (default: None)
```

**Comment by complexlogic** [comment]
Other users have requested this feature (#78).

I'm OK with adding this to the program, but I will implement as a simple boolean switch only. I don't see the value in supporting a custom offset in seconds, and it would add unneeded complexity to the program.
