### ISSUE TITLE
Is it possible to enable preserve mtimes in easy mode?

### ISSUE THREAD

**Issue by line72** [complexlogic/loudgain#98]
I am planning to run rsgain across my whole collection, so easy mode _seems_ like the best option. However, I don't want mtimes to change, as I like to sort my music based on how recently it was updated. Is there a way to enable the preserve mtime option in easy mode?

**Comment by complexlogic** [comment]
It is possible using the scan presets feature. Take the `default.ini` scan preset that ships with the program, under the `Global` section, change the `PreserveMtimes` setting from false to true, then save as a new file. When you use the program, invoke the preset with the `-p` option and the path to the new preset file as the argument.
